version: "2"
services:
  node_frontend:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules/
    ports:
      - "8080:8080"
      - "3000:3000"